config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  resources :pictures do
      member do
          put 'vote'
          get 'list'
      end
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  # photoをattachファイルとする。stylesで画像サイズを定義できる
  has_attached_file :photo, styles: { large: "700x300", medium: "300x300>", thumb: "100x100>" }

  # ファイルの拡張子を指定（これがないとエラーが発生する）
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates :name, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :photo, presence: true
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy, :vote]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.order('like DESC')
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        
        format.html { redirect_to pictures_url, notice: "投稿が完了しました" }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote 
    
    id = params[:id]
    key = "vote_"+ id

    
    
    if cookies[key] == "1"
        alert = '1枚の写真には1回しか投票できません'
        redirect_to pictures_url, alert: alert
    else
        notice = @picture.title + 'に投票しました'
        redirect_to pictures_url, notice: notice
        cookies[key] = 1
        @picture.increment(:like)
        @picture.save
    end

      
  end 

  def list
    @pictures = Picture.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
        id = params[:id]
        if integer_string?(id)
          @picture = Picture.find(params[:id])
        end


    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :photo, :title, :description)
    end

    def integer_string?(str)
        Integer(str)
        true
    rescue ArgumentError
        false
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "奄美フォトコンテスト" %></title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>


    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= pictures_path %>">奄美フォトコンテスト</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="<%= pictures_path %>">ランキング</a>
                    </li>
                    <li>
                    <a href="<%= new_picture_path %>">写真投稿</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
          <%= yield %>

    </div>
    <!-- /.container -->


</body>




</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <%= f.label :name, "名前" %><br>
      <%= f.text_field :name , :class => "form-control", :style => 'width: 400px;display: inline-block;'%>
  </div>
  <div class="field">
    <%= f.label :title, "タイトル"%><br>
      <%= f.text_field :title , :class => "form-control", :style => 'width: 400px;display: inline-block;'%>
  </div>
  <div class="field">
    <%= f.label :description, "説明"%><br>
    <%= f.text_area:description  , :size => "20x6", :class => "form-control", :style => 'width: 400px;display: inline-block;'%>
  </div>
   <div class="field">
      <%= f.file_field :photo , :class => "form-control", :style => 'width: 400px;display: inline-block;'%>
    </div>
    <br><br>
  <div class="actions">
      <%= f.submit '投稿する', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p class="bg-success" id="notice"><%= notice %></p>
<p class="bg-danger" id="alert"><%= alert %></p>



        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">奄美写真ランキング
                </h1>
            </div>
        </div>
        <!-- /.row -->

    <% i = 0 %>
    <% @pictures.each do |picture| %>
        <% i += 1 %>
        <!-- Project One -->
        <div class="row">
            <div class="col-md-7">
                <%= image_tag picture.photo.url(:large), :class => 'img-responsive' %>
            </div>
            <div class="col-md-5">
                <h3>No.<%= i %> 『<%= picture.title%>』</h3>
                <p><%= picture.description%></p>
                <p class="text-primary">by <%= picture.name%>さん</p>
                    <i style="color:yellow;" class="fa fa-star fa-2x"></i>
                    <label style="font-size:x-large;"><%= picture.like %></label>
                &nbsp;&nbsp;<a class="btn btn-xs btn-primary" style="color:white;" href="/pictures/<%= picture.id%>/vote" data-method="put" rel="nofollow">
                    投票する
                </a>
            </div>
        </div>
        <hr>
        <!-- /.row -->
    <% end %>

app/views/pictures/list.html.erb
<%= link_to 'New Picture', new_picture_path %>
<p id="notice"><%= notice %></p>

<h1>Listing Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.name %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pictures/new.html.erb
<h1>奄美で撮った写真を投稿しましょう！</h1>
<br>
<%= render 'form' %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>
<p>
   <strong>Picture:</strong>
   <!--- Modelのstyleで指定した :midium など渡すことでサイズを指定できる -->
   <%= image_tag @picture.photo.url(:medium) %>
</p>
<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>